spring.application.name=Quiz

# PostgreSQL DataSource (Neon Cloud)
spring.datasource.url=${DB_URL:jdbc:postgresql://ep-dark-dew-aowzd333.c-2.ap-southeast-1.aws.neon.tech/neondb?sslmode=require}
spring.datasource.username=${DB_USERNAME:neondb_owner}
spring.datasource.password=${DB_PASSWORD:npg_sMm2gobYU8kF}
spring.datasource.driver-class-name=org.postgresql.Driver


#  JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Spring Mail Configuration (Set these to send actual emails)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=ninajharry8@gmail.com
spring.mail.password=lsakdjfncskdfh
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

server.address=0.0.0.0

# Judge0 Cloud Compiler Configuration
# judge0.enabled=true
# judge0.url=https://judge0-ce.p.rapidapi.com
# judge0.api-key=sdfghdfasgvfdcsxfrghvdcgvgsfdcgvbfdvg
